# Generated by Django 3.2.25 on 2025-04-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250320_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_out',
            field=models.BooleanField(default=False, help_text='Mark as sold out or unavailable.'),
        ),
    ]
